target_root: "C:/PROJECTS_STRUCT"
structure:
  - "src/core/"
  - "src/utils/"
  - "src/pipelines/"
  - "scripts/"
  - "tests/unit/"
  - "tests/integration/"
  - "docs/"
  - "reports/"
  - "configs/"
  - "data/raw/"
  - "data/interim/"
  - "data/processed/"
  - "notebooks/"
  - "archive/"
  - "tmp/"
conflict_policy: "version"
mode: "move"